component: scf
name: http
inputs:
  src:
    src: ../release
    exclude:
      - .env
  type: web
  name: bestdori-ayachan
  region: ap-tokyo
  runtime: Go1
  events:
    - apigw:
        parameters:
          protocols:
            - http
            - https
          environment: release
          endpoints:
            - path: /
              method: ANY
app: http-demo
