# .github/workflows/buildAndPush.yml
name: Go Test and Docker Build and Push

on:
  push:
    tags:
      - 'v*'

jobs:
  test-and-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'

      - name: Echo Go Version
        run: go version

      - name: Run Go test in service
        run: go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Tencent Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Build and push Docker image to GHCR and TCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/6qhtsk/bestdori-proxy:latest
            ghcr.io/6qhtsk/bestdori-proxy:${{ env.VERSION }}
            ccr.ccs.tencentyun.com/project-ayachan/bestdori-proxy:latest
            ccr.ccs.tencentyun.com/project-ayachan/bestdori-proxy:${{ env.VERSION }}